config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  post 'likes/id' => "likes#toggle"

  devise_for :users
  resources :posts, only: [:index, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  #resources :likes, only: [:create, :destroy]
  
  
  root "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  has_many :likes, as: :likeable
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :user, presence: true

	belongs_to :user
	has_many :comments, dependent: :destroy

	has_many :likes, as: :likeable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes


  has_many :friendships
  has_many :friends, through: :friendships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]
  before_action :authorize_user, only: [:destroy]

  
  def create
  	@comment = Comment.new(comment_params)
  	@comment.user = current_user
  	@comment.save
  end

  def destroy
  	@post = @comment.post
  	@comment.destroy
  end

  private

  def comment_params
  	params.require(:comment).permit(:post_id, :content)
  end

  def set_comment
  	@comment = Comment.find(params[:id])
  end

  def authorize_user
  	if @comment.user != current_user
  		return redirect_to root_path
  	end
  	return true

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]
  before_action :authorize_user, only: [:destroy]
def create
end

def destroy
  end
  
  def toggle
  	@like = Like.new(like_params)
  	@comment.user = current_user
    @post = @comment.post
  	@comment.save

  	@comment.destroy
  end

  private

  def like_params
  	params.require(:like).permit(:likeable_id, :likeable_type)
  end

  def set_like
  	@comment = Comment.find(params[:id])
  end

  def authorize_user
  	if @comment.user != current_user
  		return redirect_to root_path
  	end
  	return true

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_post, only: [:destroy]
  before_action :authorize_user, only: [:destroy]

  def index
  	@post = Post.new
  	@comment = Comment.new
    @like= Like.new
  	@posts = Post.all.reverse()
  end

  def create
  	@post = Post.new(post_params)
  	@post.user = current_user
  	@post.save
    @like = Like.new
  	@comment = Comment.new
  end

  def destroy
    @post_id = @post.id
  	@post.destroy
  	
  end

  private

  def post_params
  	params.require(:post).permit(:content)
  end

  def set_post
  	@post = Post.find(params[:id])
  end

  def authorize_user
  	if @post.user != current_user
  		return redirect_to root_path
  	end
  	return true

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li id= "comment-<%= com.id %>" >
				<div>
					<p>
					<%= com.content %>
					</p>
					<p class="author-details"><%= com.user.email%> at <%= com.created_at %>
					</p>
				</div>
				
				<p class="comment-destroy-link">
					<%= link_to "X", comment_path(com.id), remote: true, method: :delete %>
				</p>
			</li>

app/views/comments/create.js.erb
$('#comments-list-<%= @post.id %>').prepend("<%= escape_javascript render 'comment', com: @comment %>");

console.log("HERE");

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();

app/views/comments/index.html.erb
<main>
	<div id='comments-list-container'>
		<ul id="comments-list">
			<% @comments.each do |comment| %>
			<% render 'comment' , com: comment %>
			<% end %>
		</ul>
	</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Allsocial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'components/test', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'components/test', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header id="body-header">
		<div id="page-logo">
			<%= link_to "/" do%>
				<%= image_tag("reddit-logo.png") %>
			<% end %>
		</div>

		<div id="auth-links">
			<ul>
				<% if !user_signed_in? %>
					<% if !current_page?(new_user_session_path) %>
					<li>
						<p>
							<%= link_to "Sign In", new_user_session_path %>
						</p>
					</li>
					<% end %>
					<% if !current_page?(new_user_registration_path) %>
					<li>
						<p>
							<%= link_to "Sign Up", new_user_registration_path %>
						</p>
					</li>
					<% end %>
				<% else %>
				<li>
					<p><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
				</li>
				<% end %>
				
			</ul>
		</div>
	</header>

<%= yield %>

</body>
</html>

app/views/likes/toggle.js.erb
console.log("GGGG");

app/views/posts/_post.html.erb
<li id="post-<%= p.id %>" class="post">
	<div class="post-content">
		<div class="text">
			<p >
				<%= p.content %>
			</p>
			<p class="author-details">
				<%= p.user.email%> at <%= p.created_at %>
			</p>
		</div>

		<p>
			<%= link_to "Like" , likes_id_path(p.id), remote: true, method: :post %>
		</p>
		<!-- 
            <form class="new_like" id="new_like" action="/likes" accept-charset="UTF-8" data-remote="true" method="post">
	        <input name="utf8" type="hidden" value="✓">
		    <input value="<%= p.id %>" type="hidden" name="like[likeable_id]" id="like_likeable_id">
		    <input value="post" type="hidden" name="like[likeable_type]" id="like_likeable_id">
			<input type="submit" name="commit" value="Like"> 
            </form> -->

<!--          <a href="/posts/<%= p.id %>" data-remote="true" rel="nofollow" data-method="delete" ><img src="/assets/thumbs-up.png" width="50" height="50" ></a>
 -->
		<p class="post-destroy-link">
			<%= link_to "X", post_path(p.id), remote: true, method: :delete %>
		</p>
	</div>
	<div class="post-comments-container">
			<%= form_for @comment, remote: true do |f| %>
			<%= f.hidden_field :post_id, value: p.id %>
			<%= f.text_area :content, placeholder: "Add Comment" %>
			<%= f.submit %>
		<% end %>

		<ul id="comments-list-<%= p.id %>">
			<% p.comments.each do |com| %>
			<li id= "comment-<%= com.id %>" >
				<div>
					<p>
					<%= com.content %>
					</p>
					<p class="author-details"><%= com.user.email%> at <%= com.created_at %>
					</p>
					<button class="button" id="like_comment-<%= com.id%>"  >Like</button>
					
				</div>
				
				<p class="comment-destroy-link">
					<%= link_to "X", comment_path(com.id), remote: true, method: :delete %>
				</p>
			</li>
			<% end %>
		</ul>
	</div>
</li>

app/views/posts/create.html.erb
something

app/views/posts/create.js.erb
$('#posts-list').prepend("<%= escape_javascript  render 'post', p: @post %>");

app/views/posts/destroy.js.erb
$('#post-<%= @post_id %>').remove();

app/views/posts/index.html.erb
<main>

	<% if user_signed_in? %>
	<div id="new-post-form-container">
		<%= form_for @post, remote: true do |f| %>
			<%= f.label :content, "Add Post" %>
			<%= f.text_area :content, placeholder: "Type Here" %>
			<%= f.submit %>
		<% end %>
	</div>
	<% end %>

	<div id="posts-list-container">
		<ul id="posts-list">
			<% @posts.each do |post| %>
				<%= render 'post' , p: post %>
			<% end %>
		</ul>
	</div>


</main>